### ISSUE TITLE
Suggestion: Use the same case as native powershell does

### ISSUE THREAD

**Issue by Splaxi** [darrenjrobinson/JWTDetails#2]
I would recommend that you try to implement the same case as native powershell commands use.

https://github.com/PoshCode/PowerShellPracticeAndStyle

Your function name should be: Get-JWTDetails 
Your parameter name should be: $Token

And your example should be without the parentheses, because they might confuse the native powershell user.

```
Get-JWTDetails -Token 'eyJ0eXAiOi........XmN4GnWQAw7OwMA'

OR

'eyJ0eXAiOi........XmN4GnWQAw7OwMA' | Get-JWTDetails 

OR 

Get-JWTDetails 'eyJ0eXAiOi........XmN4GnWQAw7OwMA'
#Will require the Position attribute for the parameter. Which is included in my PR.
```

**Comment by darrenjrobinson** [comment]
Completed in commit https://github.com/darrenjrobinson/JWTDetails/commit/4ddd967aca3875187ea0f206fd60a5e6eba124d2
