### ISSUE TITLE
ExpiryDateTime error

### ISSUE THREAD

**Issue by arjunprasada** [darrenjrobinson/JWTDetails#3]
In following line the the UTC offset that was picked was only in hours
$hoursOffset = $timeZone.GetUtcOffset($(Get-Date)).hours

So people from locations like in India where the BaseUtcOffSet is +5:30
only +5 hours is getting added, so expiryDateTime and timeToExpiry shows half an hour less time

**Comment by darrenjrobinson** [comment]
thx for logging the issue. 
I can see what the fix is. 
Will combine the fix with an update to also code-sign the module in the next couple of weeks.

**Comment by darrenjrobinson** [comment]
Updated to address timezone issue, and code sign. 
https://github.com/darrenjrobinson/JWTDetails/commit/72cef7bb7c8135177c741ce830a1efe92557fcd3
